apiVersion: v1
description: A Helm chart to run the Fairwinds Insights agent
name: insights-agent
version: 1.1.0
appVersion: 2.1.0
maintainers:
  - name: rbren
  - name: makoscafee
  - name: baderbuddy
